# Generated by Django 4.2 on 2026-04-13 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_choice', models.CharField(choices=[('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissors')], max_length=1)),
                ('cpu_choice', models.CharField(choices=[('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissors')], max_length=1)),
                ('result', models.CharField(choices=[('W', 'Win'), ('L', 'Loss'), ('D', 'Draw')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Game Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
